import 'dart:convert';
import 'package:fabricproject/common/api_endpoint.dart';
import 'package:fabricproject/models/internal_companies_model.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:http/http.dart' as http;

final internalCompanyProvider = FutureProvider<List<Data>>((ref) async {
  final response = await http.get(Uri.parse(baseURL + getCompany));

  if (response.statusCode == 200) {
    final Map<String, dynamic> json = jsonDecode(response.body);
    final autogenerated = Autogenerated.fromJson(json);
    return autogenerated.data ?? [];
  } else {
    throw Exception('Failed to load data');
  }
});
